-- menu_items table seeds here
--Descriptions taken from the Starbucks menu
INSERT INTO menu_items (name, price, picture_url, prep_time, description, in_stock, category) VALUES ('Americano', 176, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80', 3, 'Espresso shots topped with hot water create a light layer of crema culminating in this wonderfully rich cup with depth and nuance.', TRUE, 'Coffee');
INSERT INTO menu_items (name, price, picture_url, prep_time, description, in_stock, category) VALUES ('Cappuccino', 355, 'https://images.unsplash.com/photo-1572309148120-e18fa3b0c9f6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=564&q=80', 6, 'Dark, rich espresso lies in wait under a smoothed and stretched layer of thick milk foam. An alchemy of barista artistry and craft.', TRUE, 'Coffee');
INSERT INTO menu_items (name, price, picture_url, prep_time, description, in_stock, category) VALUES ('Espresso', 288, 'https://images.unsplash.com/photo-1502849394214-c4b6352145ee?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=662&q=80', 3, 'Our smooth signature Espresso Roast with rich flavour and caramelly sweetness is at the very heart of everything we do.', TRUE, 'Coffee');

--Descriptions taken from the Krispy Kreme menu
INSERT INTO menu_items (name, price, picture_url, prep_time, description, in_stock, category) VALUES ('Plain Donut', 567, 'https://images.unsplash.com/photo-1568148847348-1c03e5cc84d9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=640&q=80', 3, 'Our classic plain donut is tossed in cinnamon sugar for a perfectly simple treat.', TRUE, 'Bakery');

--Descriptions taken from the Starbucks menu
INSERT INTO menu_items (name, price, picture_url, prep_time, description, in_stock, category) VALUES ('Chocolate Muffin', 741, 'https://images.unsplash.com/photo-1582623203765-511e04ff6948?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80', 3, 'Our buttermilk muffin stands apart with its unique recipe—specially made with rich sour cream, packed full of semisweet chocolate chips and chunks and finished with a touch of sea-salty goodness.', TRUE, 'Bakery');
